name: sample run

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch 
        uses: actions/checkout@v2
      
      - name: print 
        run: echo "Hello World!"
        