name: sample run

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event
        run: echo "${{ toJSON(github.event) }}"

      - name: checkout branch 
        uses: actions/checkout@v2
      
      - name: print 
        run: echo "Hello World!"

      - uses: actions/setup-node@v4
        with:
          node-version: 24

  