name: sample run

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
      - name: checkout branch 
        uses: actions/checkout@v2
      
      - name: print 
        run: echo "Hello World!"

      - uses: actions/setup-node@v4
        with:
          node-version: 24
  middle:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch 
        uses: actions/checkout@v2
      
      - name: print 
        run: echo "Hello World!"

      - uses: actions/setup-node@v6
        with:
          node-version: 24
  
