name: Dependabot auto merge PRs

on:
  check_suite:
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event
        run: echo "${{ toJSON(github.event) }}"
